export const Images = {
  //PNG
  common: require('../assets/Images/common.png'),
  demo: require('../assets/Images/demo.png'),
  logo: require('../assets/Images/logo.png'),
  background: require('../assets/Images/background.png'),
  home: require('../assets/Images/home.png'),
  home_selected: require('../assets/Images/home_selected.png'),
  categories: require('../assets/Images/categories.png'),
  categories_selected: require('../assets/Images/categories_selected.png'),
  about: require('../assets/Images/about.png'),
  about_selected: require('../assets/Images/about_selected.png'),
  search: require('../assets/Images/search.png'),
  back: require('../assets/Images/back.png'),
  next: require('../assets/Images/next.png'),
  about_detail: require('../assets/Images/about_detail.png'),
  filter: require('../assets/Images/filter.png'),
  location: require('../assets/Images/location.png'),
  website: require('../assets/Images/website.png'),
  location_name: require('../assets/Images/location_name.png'),
  mail: require('../assets/Images/mail.png'),
  contact: require('../assets/Images/contact.png'),
  cross: require('../assets/Images/cross.png'),
  checkboxselected: require('../assets/Images/checkboxselected.png'),
  soupbowls: require('../assets/Images/soupbowls.png'),
  softservestation: require('../assets/Images/softservestation.png'),
  joyfultaste: require('../assets/Images/joyfultaste.png'),
  deliciosocafe: require('../assets/Images/deliciosocafe.png'),
  placeholder: require('../assets/Images/placeholder.png'),

  //SVG
  food: require('../assets/Images/food.png'),
};
